<HTML>
<HEAD>
    <META CHARSET="UTF-8">
    <META NAME="VIEWPORT" CONTENT="WIDTH=DEVICE-WIDTH, INITIAL-SCALE=1.0">
    <META HTTP-EQUIV="X-UA-COMPATIBLE" CONTENT="IE=EDGE">
    <TITLE>WEB COMPRAS</TITLE>
    <LINK REL="STYLESHEET" HREF="BOOTSTRAP.MIN.CSS">
</HEAD>

<BODY>
<H1>ALTA PRODUCTOS - DAVID PEREZ</H1>
<?PHP
INCLUDE "conexion.php";


/* SE MUESTRA EL FORMULARIO LA PRIMERA VEZ */
IF (!ISSET($_POST) || EMPTY($_POST)) { 
    $CATEGORIAS = OBTENERCATEGORIA($DB);
    /* SE INICIALIZA LA LISTA VALORES*/
	ECHO '<FORM ACTION="" METHOD="POST">';
?>
<DIV CLASS="CONTAINER ">
<!--APLICACION-->
<DIV CLASS="CARD BORDER-SUCCESS MB-3" STYLE="MAX-WIDTH: 30REM;">
<DIV CLASS="CARD-HEADER">DATOS PRODUCTO</DIV>
<DIV CLASS="CARD-BODY">
		<DIV CLASS="FORM-GROUP">
        ID PRODUCTO <INPUT TYPE="TEXT" NAME="IDPRODUCTO" PLACEHOLDER="IDPRODUCTO" CLASS="FORM-CONTROL">
        </DIV>
		<DIV CLASS="FORM-GROUP">
        NOMBRE PRODUCTO <INPUT TYPE="TEXT" NAME="NOMBRE" PLACEHOLDER="NOMBRE" CLASS="FORM-CONTROL">
        </DIV>
		<DIV CLASS="FORM-GROUP">
        PRECIO PRODUCTO <INPUT TYPE="TEXT" NAME="PRECIO" PLACEHOLDER="PRECIO" CLASS="FORM-CONTROL">
        </DIV>
        <DIV>
        <LABEL FOR="CATEGORIA">CATEGORIAS:</LABEL>
	<SELECT NAME="CATEGORIA">
		<?PHP FOREACH($CATEGORIAS AS $CATEGORIA) : ?>
			<OPTION> <?PHP ECHO $CATEGORIA ?> </OPTION>
		<?PHP ENDFOREACH; ?>
	</SELECT>
	<BR>
        </DIV>
	</BR>
<?PHP
	ECHO '<DIV><INPUT TYPE="SUBMIT" VALUE="ALTA PRODUCTO"></DIV>
	</FORM>';
} ELSE { 
$IDPRODUCTO=$_POST['IDPRODUCTO'];
$NOMBRE=$_POST['NOMBRE'];
$PRECIO=$_POST['PRECIO'];
$CATES=$_POST['CATEGORIA'];
$SQL3 = "SELECT ID_CATEGORIA FROM CATEGORIA WHERE NOMBRE = '$CATES'";
$CATEGO = $DB->QUERY($SQL3);
IF ( $CATEGO ) {
WHILE ($ROW = MYSQLI_FETCH_ASSOC($CATEGO)) {
        $CATE = $ROW['ID_CATEGORIA'];
    }
    }
CREARPRODUCTO($IDPRODUCTO,$NOMBRE,$PRECIO,$CATE,$db);	
}
?>

<?PHP
// FUNCIONES UTILIZADAS EN EL PROGRAMA
FUNCTION OBTENERCATEGORIA($DB){
    $CATEGORIA = ARRAY();	
	$SQL = "SELECT NOMBRE FROM CATEGORIA";
	$RESULTADO = MYSQLI_QUERY($DB, $SQL);
	IF ($RESULTADO) {
		WHILE ($ROW = MYSQLI_FETCH_ASSOC($RESULTADO)) {
			$CATEGORIA[] = $ROW['NOMBRE'];
		}
	}
	RETURN $CATEGORIA;
}
FUNCTION CREARPRODUCTO($ID,$NOM,$PRE,$CATE,$DB){
    $SQL = "INSERT INTO PRODUCTO VALUES('$ID','$NOM','$PRE','$CATE')";
    MYSQLI_QUERY($DB,$SQL);
}


	




?>



</BODY>

</HTML>
